version: '3.9'

services:
  #new service (java_app)
  java_app:
    container_name: java_app
    image: usuario-ws
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
    networks:
      - postgres-back

  #old service (postgres)
  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-back
volumes:
  pgdata: {}
networks:
  postgres-back:
    driver: bridge